### ISSUE TITLE
Passing string to ch should throw exception

### ISSUE THREAD

**Issue by AleksandarDev** [wedranb/trim-left-by-char#1]
User should be notified when they pass invalid trim char (eg. ch.length > 1)

Example:

    t.is(trimLeftByChar('\r\ntest', '\r\n'), 'test');

**Comment by wedranb** [comment]
It should be [solved](https://github.com/wedranb/trim-left-by-char/commit/a7930454031147a7ae7d4aac4880d766c620d1d6).

You can verify.

**Comment by AleksandarDev** [comment]
a793045 Confirmed
